// Middleton Finance Suite — Auto-generated by 02_export_dashboard_data.py
// Do not edit manually. Rerun the script to refresh from source databases.

const MFS = {
  "kpi_pricing": {
    "total_rev_b": 0.352,
    "blended_disc": 9.46,
    "blended_gm": 32.67,
    "rebate_accrual_mm": 10.57,
    "partner_count": 12.0
  },
  "by_category": [
    {
      "product_category": "GPUs",
      "orders": 935,
      "net_rev_mm": 517.45,
      "act_disc": 9.47,
      "plan_disc": 8.97,
      "variance_pp": 0.51,
      "act_gm": 31.32,
      "target_gm": 35.0
    },
    {
      "product_category": "Adaptive Computing",
      "orders": 956,
      "net_rev_mm": 217.18,
      "act_disc": 9.76,
      "plan_disc": 9.27,
      "variance_pp": 0.49,
      "act_gm": 33.32,
      "target_gm": 40.0
    },
    {
      "product_category": "CPUs",
      "orders": 952,
      "net_rev_mm": 167.19,
      "act_disc": 9.62,
      "plan_disc": 9.12,
      "variance_pp": 0.5,
      "act_gm": 35.64,
      "target_gm": 38.0
    },
    {
      "product_category": "Semi-Custom",
      "orders": 1025,
      "net_rev_mm": 86.43,
      "act_disc": 9.59,
      "plan_disc": 9.14,
      "variance_pp": 0.45,
      "act_gm": 24.58,
      "target_gm": 28.0
    },
    {
      "product_category": "Embedded",
      "orders": 932,
      "net_rev_mm": 49.53,
      "act_disc": 9.52,
      "plan_disc": 9.06,
      "variance_pp": 0.45,
      "act_gm": 39.05,
      "target_gm": 42.0
    }
  ],
  "by_quarter": [
    {
      "quarter": "Q1 2024",
      "orders": 407,
      "net_rev_mm": 84.28,
      "act_disc": 9.57,
      "plan_disc": 9.07,
      "avg_gm": 32.58
    },
    {
      "quarter": "Q2 2024",
      "orders": 400,
      "net_rev_mm": 93.04,
      "act_disc": 9.48,
      "plan_disc": 9.05,
      "avg_gm": 32.82
    },
    {
      "quarter": "Q3 2024",
      "orders": 422,
      "net_rev_mm": 93.44,
      "act_disc": 9.11,
      "plan_disc": 8.62,
      "avg_gm": 32.65
    },
    {
      "quarter": "Q4 2024",
      "orders": 397,
      "net_rev_mm": 81.46,
      "act_disc": 9.71,
      "plan_disc": 9.27,
      "avg_gm": 32.62
    }
  ],
  "rebate_partners": [
    {
      "channel_partner": "Avnet",
      "tier": "Silver",
      "net_rev_mm": 102.26,
      "rebate_rate": 0.03,
      "mdf_eligible": "Yes"
    },
    {
      "channel_partner": "World Wide Technology",
      "tier": "Gold",
      "net_rev_mm": 96.91,
      "rebate_rate": 0.05,
      "mdf_eligible": "No"
    },
    {
      "channel_partner": "SHI International",
      "tier": "Gold",
      "net_rev_mm": 91.33,
      "rebate_rate": 0.05,
      "mdf_eligible": "Yes"
    },
    {
      "channel_partner": "TD Synnex",
      "tier": "Bronze",
      "net_rev_mm": 90.6,
      "rebate_rate": 0.015,
      "mdf_eligible": "Yes"
    },
    {
      "channel_partner": "PC Mall Gov",
      "tier": "Gold",
      "net_rev_mm": 87.09,
      "rebate_rate": 0.05,
      "mdf_eligible": "Yes"
    },
    {
      "channel_partner": "CDW",
      "tier": "Silver",
      "net_rev_mm": 85.61,
      "rebate_rate": 0.03,
      "mdf_eligible": "Yes"
    },
    {
      "channel_partner": "Arrow Electronics",
      "tier": "Gold",
      "net_rev_mm": 82.99,
      "rebate_rate": 0.05,
      "mdf_eligible": "Yes"
    },
    {
      "channel_partner": "Presidio",
      "tier": "Bronze",
      "net_rev_mm": 82.78,
      "rebate_rate": 0.015,
      "mdf_eligible": "Yes"
    },
    {
      "channel_partner": "Trace3",
      "tier": "Bronze",
      "net_rev_mm": 81.71,
      "rebate_rate": 0.015,
      "mdf_eligible": "Yes"
    },
    {
      "channel_partner": "Insight Direct",
      "tier": "Gold",
      "net_rev_mm": 81.4,
      "rebate_rate": 0.05,
      "mdf_eligible": "Yes"
    },
    {
      "channel_partner": "Ingram Micro",
      "tier": "Bronze",
      "net_rev_mm": 81.14,
      "rebate_rate": 0.015,
      "mdf_eligible": "No"
    },
    {
      "channel_partner": "Connection",
      "tier": "Silver",
      "net_rev_mm": 73.97,
      "rebate_rate": 0.03,
      "mdf_eligible": "Yes"
    }
  ],
  "kpi_deals": {
    "pipeline_b": 2.462,
    "weighted_mm": 1230.6,
    "approved": 443.0,
    "escalated": 557.0,
    "rejected": 200.0,
    "closed_won_mm": 598.3,
    "closed_won_count": 294.0,
    "closed_won_gm": 38.0
  },
  "by_stage": [
    {
      "deal_stage": "Closed Won",
      "deals": 294,
      "pipeline_mm": 598.33,
      "avg_gm": 37.99,
      "avg_win_prob": 98.8
    },
    {
      "deal_stage": "Proposal",
      "deals": 254,
      "pipeline_mm": 509.79,
      "avg_gm": 37.97,
      "avg_win_prob": 45.1
    },
    {
      "deal_stage": "Qualified",
      "deals": 212,
      "pipeline_mm": 435.19,
      "avg_gm": 37.92,
      "avg_win_prob": 25.0
    },
    {
      "deal_stage": "Negotiation",
      "deals": 181,
      "pipeline_mm": 387.64,
      "avg_gm": 38.58,
      "avg_win_prob": 70.0
    },
    {
      "deal_stage": "Closed Lost",
      "deals": 123,
      "pipeline_mm": 271.3,
      "avg_gm": 37.96,
      "avg_win_prob": 1.2
    },
    {
      "deal_stage": "Prospect",
      "deals": 136,
      "pipeline_mm": 259.53,
      "avg_gm": 37.31,
      "avg_win_prob": 9.9
    }
  ],
  "approval_dist": [
    {
      "recommendation": "Approve",
      "deals": 443,
      "pct": 36.9,
      "avg_score": 7.16,
      "total_mm": 905.81
    },
    {
      "recommendation": "Escalate",
      "deals": 557,
      "pct": 46.4,
      "avg_score": 5.8,
      "total_mm": 1156.81
    },
    {
      "recommendation": "Reject",
      "deals": 200,
      "pct": 16.7,
      "avg_score": 4.48,
      "total_mm": 399.16
    }
  ],
  "top_deals": [
    {
      "deal_id": "DEAL-5613",
      "deal_stage": "Closed Lost",
      "product_category": "Semi-Custom",
      "region": "East",
      "channel_partner": "Avnet",
      "net_val_k": 1180.0,
      "disc_pct": 8.8,
      "gm_pct": 42.9,
      "score": 8.9,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-6024",
      "deal_stage": "Negotiation",
      "product_category": "Adaptive Computing",
      "region": "West",
      "channel_partner": "Avnet",
      "net_val_k": 788.0,
      "disc_pct": 5.4,
      "gm_pct": 47.0,
      "score": 8.7,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-6028",
      "deal_stage": "Proposal",
      "product_category": "Adaptive Computing",
      "region": "Central",
      "channel_partner": "Arrow Electronics",
      "net_val_k": 3759.0,
      "disc_pct": 7.4,
      "gm_pct": 45.2,
      "score": 8.7,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-6171",
      "deal_stage": "Negotiation",
      "product_category": "Semi-Custom",
      "region": "West",
      "channel_partner": "Insight Direct",
      "net_val_k": 821.0,
      "disc_pct": 10.6,
      "gm_pct": 45.4,
      "score": 8.6,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5295",
      "deal_stage": "Closed Won",
      "product_category": "Adaptive Computing",
      "region": "East",
      "channel_partner": "Connection",
      "net_val_k": 428.0,
      "disc_pct": 5.1,
      "gm_pct": 45.8,
      "score": 8.5,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5955",
      "deal_stage": "Closed Lost",
      "product_category": "Embedded",
      "region": "South",
      "channel_partner": "Presidio",
      "net_val_k": 1942.0,
      "disc_pct": 8.7,
      "gm_pct": 42.6,
      "score": 8.5,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5082",
      "deal_stage": "Qualified",
      "product_category": "CPUs",
      "region": "East",
      "channel_partner": "CDW",
      "net_val_k": 3249.0,
      "disc_pct": 7.4,
      "gm_pct": 43.9,
      "score": 8.5,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5337",
      "deal_stage": "Closed Won",
      "product_category": "Embedded",
      "region": "Central",
      "channel_partner": "World Wide Technology",
      "net_val_k": 4128.0,
      "disc_pct": 7.6,
      "gm_pct": 45.8,
      "score": 8.5,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-6075",
      "deal_stage": "Proposal",
      "product_category": "Semi-Custom",
      "region": "South",
      "channel_partner": "Trace3",
      "net_val_k": 1656.0,
      "disc_pct": 8.8,
      "gm_pct": 42.9,
      "score": 8.5,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5996",
      "deal_stage": "Proposal",
      "product_category": "GPUs",
      "region": "West",
      "channel_partner": "TD Synnex",
      "net_val_k": 2270.0,
      "disc_pct": 8.7,
      "gm_pct": 42.2,
      "score": 8.4,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5320",
      "deal_stage": "Qualified",
      "product_category": "Embedded",
      "region": "Central",
      "channel_partner": "TD Synnex",
      "net_val_k": 2716.0,
      "disc_pct": 9.3,
      "gm_pct": 43.2,
      "score": 8.4,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5639",
      "deal_stage": "Qualified",
      "product_category": "Embedded",
      "region": "South",
      "channel_partner": "TD Synnex",
      "net_val_k": 484.0,
      "disc_pct": 5.6,
      "gm_pct": 33.2,
      "score": 8.3,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-6090",
      "deal_stage": "Prospect",
      "product_category": "CPUs",
      "region": "South",
      "channel_partner": "Arrow Electronics",
      "net_val_k": 610.0,
      "disc_pct": 12.3,
      "gm_pct": 44.4,
      "score": 8.3,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-6057",
      "deal_stage": "Proposal",
      "product_category": "Semi-Custom",
      "region": "East",
      "channel_partner": "SHI International",
      "net_val_k": 2435.0,
      "disc_pct": 12.0,
      "gm_pct": 46.2,
      "score": 8.3,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5476",
      "deal_stage": "Proposal",
      "product_category": "GPUs",
      "region": "West",
      "channel_partner": "SHI International",
      "net_val_k": 3939.0,
      "disc_pct": 8.0,
      "gm_pct": 43.7,
      "score": 8.3,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-6058",
      "deal_stage": "Closed Won",
      "product_category": "Adaptive Computing",
      "region": "West",
      "channel_partner": "Arrow Electronics",
      "net_val_k": 3926.0,
      "disc_pct": 5.1,
      "gm_pct": 39.8,
      "score": 8.3,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5941",
      "deal_stage": "Qualified",
      "product_category": "CPUs",
      "region": "East",
      "channel_partner": "Trace3",
      "net_val_k": 1033.0,
      "disc_pct": 7.0,
      "gm_pct": 47.0,
      "score": 8.3,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5083",
      "deal_stage": "Qualified",
      "product_category": "CPUs",
      "region": "South",
      "channel_partner": "Connection",
      "net_val_k": 1089.0,
      "disc_pct": 5.5,
      "gm_pct": 39.6,
      "score": 8.3,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5561",
      "deal_stage": "Negotiation",
      "product_category": "Embedded",
      "region": "Central",
      "channel_partner": "TD Synnex",
      "net_val_k": 1702.0,
      "disc_pct": 11.0,
      "gm_pct": 41.2,
      "score": 8.3,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-6174",
      "deal_stage": "Closed Won",
      "product_category": "Semi-Custom",
      "region": "South",
      "channel_partner": "Avnet",
      "net_val_k": 2264.0,
      "disc_pct": 11.9,
      "gm_pct": 47.5,
      "score": 8.2,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5353",
      "deal_stage": "Proposal",
      "product_category": "GPUs",
      "region": "South",
      "channel_partner": "Ingram Micro",
      "net_val_k": 382.0,
      "disc_pct": 8.6,
      "gm_pct": 39.2,
      "score": 8.2,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5163",
      "deal_stage": "Proposal",
      "product_category": "Adaptive Computing",
      "region": "East",
      "channel_partner": "SHI International",
      "net_val_k": 2234.0,
      "disc_pct": 6.9,
      "gm_pct": 39.7,
      "score": 8.2,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5234",
      "deal_stage": "Prospect",
      "product_category": "CPUs",
      "region": "East",
      "channel_partner": "PC Mall Gov",
      "net_val_k": 1446.0,
      "disc_pct": 10.3,
      "gm_pct": 42.7,
      "score": 8.2,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-6047",
      "deal_stage": "Closed Lost",
      "product_category": "Adaptive Computing",
      "region": "West",
      "channel_partner": "Avnet",
      "net_val_k": 422.0,
      "disc_pct": 9.7,
      "gm_pct": 35.1,
      "score": 8.2,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5032",
      "deal_stage": "Closed Lost",
      "product_category": "CPUs",
      "region": "Central",
      "channel_partner": "World Wide Technology",
      "net_val_k": 3852.0,
      "disc_pct": 13.8,
      "gm_pct": 45.7,
      "score": 8.2,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5126",
      "deal_stage": "Closed Won",
      "product_category": "GPUs",
      "region": "East",
      "channel_partner": "CDW",
      "net_val_k": 2058.0,
      "disc_pct": 9.7,
      "gm_pct": 44.3,
      "score": 8.1,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5757",
      "deal_stage": "Closed Lost",
      "product_category": "Semi-Custom",
      "region": "South",
      "channel_partner": "SHI International",
      "net_val_k": 3009.0,
      "disc_pct": 10.7,
      "gm_pct": 36.0,
      "score": 8.1,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5282",
      "deal_stage": "Closed Won",
      "product_category": "Adaptive Computing",
      "region": "South",
      "channel_partner": "SHI International",
      "net_val_k": 3474.0,
      "disc_pct": 5.0,
      "gm_pct": 41.2,
      "score": 8.1,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5696",
      "deal_stage": "Proposal",
      "product_category": "Embedded",
      "region": "Central",
      "channel_partner": "TD Synnex",
      "net_val_k": 3907.0,
      "disc_pct": 7.5,
      "gm_pct": 47.2,
      "score": 8.1,
      "recommendation": "Approve"
    },
    {
      "deal_id": "DEAL-5772",
      "deal_stage": "Qualified",
      "product_category": "Semi-Custom",
      "region": "South",
      "channel_partner": "Presidio",
      "net_val_k": 4178.0,
      "disc_pct": 11.0,
      "gm_pct": 46.4,
      "score": 8.1,
      "recommendation": "Approve"
    }
  ],
  "loss_reasons": [
    {
      "loss_reason": "No decision",
      "lost_deals": 27,
      "lost_mm": 62.15
    },
    {
      "loss_reason": "Budget cut",
      "lost_deals": 21,
      "lost_mm": 45.92
    },
    {
      "loss_reason": "Competition",
      "lost_deals": 18,
      "lost_mm": 44.26
    },
    {
      "loss_reason": "Price",
      "lost_deals": 18,
      "lost_mm": 39.2
    },
    {
      "loss_reason": "Technical fit",
      "lost_deals": 19,
      "lost_mm": 37.79
    }
  ],
  "kpi_channel": {
    "total_rev_mm": 83.5,
    "avg_attainment": 96.2,
    "reps_at_quota": 5.0,
    "total_reps": 12.0,
    "avg_gm": 35.6,
    "top_attainment": 126.6,
    "top_rep": "Tyler Brooks"
  },
  "reps": [
    {
      "rep_name": "Tyler Brooks",
      "region": "Central",
      "segment": "SMB",
      "quota_mm": 9.66,
      "actual_mm": 12.23,
      "attainment": 126.6,
      "var_mm": 2.57,
      "avg_deal_k": 201.0,
      "win_rate": 76.9,
      "disc_pct": 12.4,
      "gm_pct": 44.0
    },
    {
      "rep_name": "Mei-Lin Park",
      "region": "East",
      "segment": "SMB",
      "quota_mm": 8.29,
      "actual_mm": 9.88,
      "attainment": 119.2,
      "var_mm": 1.59,
      "avg_deal_k": 506.0,
      "win_rate": 79.2,
      "disc_pct": 17.9,
      "gm_pct": 33.2
    },
    {
      "rep_name": "Sofia Delgado",
      "region": "East",
      "segment": "Public Sector",
      "quota_mm": 6.83,
      "actual_mm": 8.04,
      "attainment": 117.8,
      "var_mm": 1.21,
      "avg_deal_k": 238.0,
      "win_rate": 68.8,
      "disc_pct": 12.0,
      "gm_pct": 39.9
    },
    {
      "rep_name": "Kenji Tanaka",
      "region": "South",
      "segment": "Enterprise",
      "quota_mm": 11.8,
      "actual_mm": 13.47,
      "attainment": 114.2,
      "var_mm": 1.67,
      "avg_deal_k": 548.0,
      "win_rate": 75.0,
      "disc_pct": 13.4,
      "gm_pct": 28.3
    },
    {
      "rep_name": "Carlos Rivera",
      "region": "Central",
      "segment": "Enterprise",
      "quota_mm": 3.18,
      "actual_mm": 3.6,
      "attainment": 113.3,
      "var_mm": 0.42,
      "avg_deal_k": 560.0,
      "win_rate": 60.0,
      "disc_pct": 13.0,
      "gm_pct": 35.5
    },
    {
      "rep_name": "Natalie Frost",
      "region": "South",
      "segment": "SMB",
      "quota_mm": 6.36,
      "actual_mm": 6.15,
      "attainment": 96.7,
      "var_mm": -0.21,
      "avg_deal_k": 238.0,
      "win_rate": 67.6,
      "disc_pct": 11.2,
      "gm_pct": 34.3
    },
    {
      "rep_name": "Rachel Okafor",
      "region": "South",
      "segment": "Commercial",
      "quota_mm": 4.91,
      "actual_mm": 4.64,
      "attainment": 94.6,
      "var_mm": -0.27,
      "avg_deal_k": 519.0,
      "win_rate": 80.0,
      "disc_pct": 23.8,
      "gm_pct": 30.5
    },
    {
      "rep_name": "Aisha Johnson",
      "region": "Central",
      "segment": "Commercial",
      "quota_mm": 5.31,
      "actual_mm": 4.97,
      "attainment": 93.6,
      "var_mm": -0.34,
      "avg_deal_k": 562.0,
      "win_rate": 80.0,
      "disc_pct": 17.0,
      "gm_pct": 40.9
    },
    {
      "rep_name": "Priya Nair",
      "region": "West",
      "segment": "Commercial",
      "quota_mm": 7.16,
      "actual_mm": 5.36,
      "attainment": 74.9,
      "var_mm": -1.8,
      "avg_deal_k": 168.0,
      "win_rate": 62.0,
      "disc_pct": 17.3,
      "gm_pct": 34.2
    },
    {
      "rep_name": "Derek Walsh",
      "region": "West",
      "segment": "Public Sector",
      "quota_mm": 5.43,
      "actual_mm": 3.94,
      "attainment": 72.4,
      "var_mm": -1.5,
      "avg_deal_k": 269.0,
      "win_rate": 77.8,
      "disc_pct": 17.2,
      "gm_pct": 41.3
    },
    {
      "rep_name": "Marcus Chen",
      "region": "East",
      "segment": "Enterprise",
      "quota_mm": 9.57,
      "actual_mm": 6.92,
      "attainment": 72.3,
      "var_mm": -2.65,
      "avg_deal_k": 202.0,
      "win_rate": 60.7,
      "disc_pct": 22.7,
      "gm_pct": 31.8
    },
    {
      "rep_name": "Jordan Mitchell",
      "region": "West",
      "segment": "Enterprise",
      "quota_mm": 7.35,
      "actual_mm": 4.28,
      "attainment": 58.2,
      "var_mm": -3.07,
      "avg_deal_k": 351.0,
      "win_rate": 80.0,
      "disc_pct": 24.1,
      "gm_pct": 32.8
    }
  ],
  "monthly": [
    {
      "month": "2024-01",
      "actual_mm": 7.09,
      "plan_mm": 6.78,
      "var_mm": 0.31,
      "disc_pct": 15.77,
      "gm_pct": 33.83
    },
    {
      "month": "2024-02",
      "actual_mm": 6.63,
      "plan_mm": 7.04,
      "var_mm": -0.41,
      "disc_pct": 15.42,
      "gm_pct": 36.49
    },
    {
      "month": "2024-03",
      "actual_mm": 6.58,
      "plan_mm": 7.12,
      "var_mm": -0.54,
      "disc_pct": 14.91,
      "gm_pct": 31.95
    },
    {
      "month": "2024-04",
      "actual_mm": 6.52,
      "plan_mm": 7.06,
      "var_mm": -0.54,
      "disc_pct": 18.69,
      "gm_pct": 36.44
    },
    {
      "month": "2024-05",
      "actual_mm": 6.91,
      "plan_mm": 7.12,
      "var_mm": -0.2,
      "disc_pct": 16.47,
      "gm_pct": 32.59
    },
    {
      "month": "2024-06",
      "actual_mm": 7.15,
      "plan_mm": 7.05,
      "var_mm": 0.1,
      "disc_pct": 16.01,
      "gm_pct": 34.17
    },
    {
      "month": "2024-07",
      "actual_mm": 7.4,
      "plan_mm": 7.64,
      "var_mm": -0.23,
      "disc_pct": 15.25,
      "gm_pct": 33.16
    },
    {
      "month": "2024-08",
      "actual_mm": 7.73,
      "plan_mm": 7.71,
      "var_mm": 0.02,
      "disc_pct": 16.46,
      "gm_pct": 34.28
    },
    {
      "month": "2024-09",
      "actual_mm": 7.76,
      "plan_mm": 7.69,
      "var_mm": 0.08,
      "disc_pct": 16.55,
      "gm_pct": 36.0
    },
    {
      "month": "2024-10",
      "actual_mm": 8.7,
      "plan_mm": 8.89,
      "var_mm": -0.19,
      "disc_pct": 19.63,
      "gm_pct": 33.45
    },
    {
      "month": "2024-11",
      "actual_mm": 9.06,
      "plan_mm": 9.06,
      "var_mm": -0.01,
      "disc_pct": 16.96,
      "gm_pct": 35.05
    },
    {
      "month": "2024-12",
      "actual_mm": 8.41,
      "plan_mm": 9.13,
      "var_mm": -0.72,
      "disc_pct": 14.37,
      "gm_pct": 31.86
    }
  ],
  "q4_close": [
    {
      "month": "2024-10",
      "rep_name": "Aisha Johnson",
      "region": "Central",
      "plan_k": 559.4,
      "actual_k": 490.3,
      "var_k": -69.0,
      "var_pct": -12.3,
      "disc_pct": 22.3,
      "gm_pct": 39.2
    },
    {
      "month": "2024-10",
      "rep_name": "Carlos Rivera",
      "region": "Central",
      "plan_k": 364.8,
      "actual_k": 307.4,
      "var_k": -57.4,
      "var_pct": -15.7,
      "disc_pct": 10.5,
      "gm_pct": 30.6
    },
    {
      "month": "2024-10",
      "rep_name": "Derek Walsh",
      "region": "West",
      "plan_k": 441.1,
      "actual_k": 441.6,
      "var_k": 0.5,
      "var_pct": 0.1,
      "disc_pct": 12.6,
      "gm_pct": 41.4
    },
    {
      "month": "2024-10",
      "rep_name": "Jordan Mitchell",
      "region": "West",
      "plan_k": 451.6,
      "actual_k": 437.8,
      "var_k": -13.7,
      "var_pct": -3.0,
      "disc_pct": 22.9,
      "gm_pct": 26.4
    },
    {
      "month": "2024-10",
      "rep_name": "Kenji Tanaka",
      "region": "South",
      "plan_k": 1366.6,
      "actual_k": 1164.5,
      "var_k": -202.1,
      "var_pct": -14.8,
      "disc_pct": 24.9,
      "gm_pct": 34.6
    },
    {
      "month": "2024-10",
      "rep_name": "Marcus Chen",
      "region": "East",
      "plan_k": 735.6,
      "actual_k": 663.1,
      "var_k": -72.5,
      "var_pct": -9.9,
      "disc_pct": 19.7,
      "gm_pct": 28.8
    },
    {
      "month": "2024-10",
      "rep_name": "Mei-Lin Park",
      "region": "East",
      "plan_k": 989.1,
      "actual_k": 1249.1,
      "var_k": 260.0,
      "var_pct": 26.3,
      "disc_pct": 22.7,
      "gm_pct": 28.0
    },
    {
      "month": "2024-10",
      "rep_name": "Natalie Frost",
      "region": "South",
      "plan_k": 673.7,
      "actual_k": 667.5,
      "var_k": -6.2,
      "var_pct": -0.9,
      "disc_pct": 20.9,
      "gm_pct": 34.1
    },
    {
      "month": "2024-10",
      "rep_name": "Priya Nair",
      "region": "West",
      "plan_k": 632.6,
      "actual_k": 475.6,
      "var_k": -157.0,
      "var_pct": -24.8,
      "disc_pct": 20.5,
      "gm_pct": 37.9
    },
    {
      "month": "2024-10",
      "rep_name": "Rachel Okafor",
      "region": "South",
      "plan_k": 473.4,
      "actual_k": 563.0,
      "var_k": 89.7,
      "var_pct": 18.9,
      "disc_pct": 18.0,
      "gm_pct": 32.4
    },
    {
      "month": "2024-10",
      "rep_name": "Sofia Delgado",
      "region": "East",
      "plan_k": 916.3,
      "actual_k": 656.9,
      "var_k": -259.4,
      "var_pct": -28.3,
      "disc_pct": 17.5,
      "gm_pct": 25.3
    },
    {
      "month": "2024-10",
      "rep_name": "Tyler Brooks",
      "region": "Central",
      "plan_k": 1282.8,
      "actual_k": 1581.7,
      "var_k": 298.9,
      "var_pct": 23.3,
      "disc_pct": 23.0,
      "gm_pct": 42.6
    },
    {
      "month": "2024-11",
      "rep_name": "Aisha Johnson",
      "region": "Central",
      "plan_k": 516.3,
      "actual_k": 645.2,
      "var_k": 128.9,
      "var_pct": 25.0,
      "disc_pct": 13.4,
      "gm_pct": 31.4
    },
    {
      "month": "2024-11",
      "rep_name": "Carlos Rivera",
      "region": "Central",
      "plan_k": 378.4,
      "actual_k": 366.6,
      "var_k": -11.8,
      "var_pct": -3.1,
      "disc_pct": 23.2,
      "gm_pct": 29.1
    },
    {
      "month": "2024-11",
      "rep_name": "Derek Walsh",
      "region": "West",
      "plan_k": 406.9,
      "actual_k": 394.5,
      "var_k": -12.4,
      "var_pct": -3.0,
      "disc_pct": 17.8,
      "gm_pct": 36.7
    },
    {
      "month": "2024-11",
      "rep_name": "Jordan Mitchell",
      "region": "West",
      "plan_k": 474.8,
      "actual_k": 369.8,
      "var_k": -105.0,
      "var_pct": -22.1,
      "disc_pct": 24.7,
      "gm_pct": 33.4
    },
    {
      "month": "2024-11",
      "rep_name": "Kenji Tanaka",
      "region": "South",
      "plan_k": 1502.9,
      "actual_k": 1562.1,
      "var_k": 59.2,
      "var_pct": 3.9,
      "disc_pct": 12.7,
      "gm_pct": 36.9
    },
    {
      "month": "2024-11",
      "rep_name": "Marcus Chen",
      "region": "East",
      "plan_k": 724.2,
      "actual_k": 672.6,
      "var_k": -51.6,
      "var_pct": -7.1,
      "disc_pct": 23.9,
      "gm_pct": 29.7
    },
    {
      "month": "2024-11",
      "rep_name": "Mei-Lin Park",
      "region": "East",
      "plan_k": 1018.9,
      "actual_k": 1138.1,
      "var_k": 119.3,
      "var_pct": 11.7,
      "disc_pct": 19.1,
      "gm_pct": 36.5
    },
    {
      "month": "2024-11",
      "rep_name": "Natalie Frost",
      "region": "South",
      "plan_k": 670.1,
      "actual_k": 761.5,
      "var_k": 91.4,
      "var_pct": 13.7,
      "disc_pct": 13.7,
      "gm_pct": 39.7
    },
    {
      "month": "2024-11",
      "rep_name": "Priya Nair",
      "region": "West",
      "plan_k": 637.3,
      "actual_k": 516.9,
      "var_k": -120.4,
      "var_pct": -18.9,
      "disc_pct": 11.6,
      "gm_pct": 41.3
    },
    {
      "month": "2024-11",
      "rep_name": "Rachel Okafor",
      "region": "South",
      "plan_k": 514.7,
      "actual_k": 418.8,
      "var_k": -95.8,
      "var_pct": -18.6,
      "disc_pct": 21.7,
      "gm_pct": 37.9
    },
    {
      "month": "2024-11",
      "rep_name": "Sofia Delgado",
      "region": "East",
      "plan_k": 832.4,
      "actual_k": 744.4,
      "var_k": -88.0,
      "var_pct": -10.6,
      "disc_pct": 11.4,
      "gm_pct": 39.5
    },
    {
      "month": "2024-11",
      "rep_name": "Tyler Brooks",
      "region": "Central",
      "plan_k": 1385.8,
      "actual_k": 1466.0,
      "var_k": 80.1,
      "var_pct": 5.8,
      "disc_pct": 10.4,
      "gm_pct": 28.6
    },
    {
      "month": "2024-12",
      "rep_name": "Aisha Johnson",
      "region": "Central",
      "plan_k": 548.9,
      "actual_k": 591.3,
      "var_k": 42.5,
      "var_pct": 7.7,
      "disc_pct": 16.5,
      "gm_pct": 28.8
    },
    {
      "month": "2024-12",
      "rep_name": "Carlos Rivera",
      "region": "Central",
      "plan_k": 406.2,
      "actual_k": 390.0,
      "var_k": -16.1,
      "var_pct": -4.0,
      "disc_pct": 10.5,
      "gm_pct": 27.9
    },
    {
      "month": "2024-12",
      "rep_name": "Derek Walsh",
      "region": "West",
      "plan_k": 433.7,
      "actual_k": 502.2,
      "var_k": 68.5,
      "var_pct": 15.8,
      "disc_pct": 13.1,
      "gm_pct": 42.8
    },
    {
      "month": "2024-12",
      "rep_name": "Jordan Mitchell",
      "region": "West",
      "plan_k": 441.5,
      "actual_k": 349.8,
      "var_k": -91.7,
      "var_pct": -20.8,
      "disc_pct": 13.7,
      "gm_pct": 28.0
    },
    {
      "month": "2024-12",
      "rep_name": "Kenji Tanaka",
      "region": "South",
      "plan_k": 1417.7,
      "actual_k": 1107.5,
      "var_k": -310.2,
      "var_pct": -21.9,
      "disc_pct": 11.8,
      "gm_pct": 27.0
    },
    {
      "month": "2024-12",
      "rep_name": "Marcus Chen",
      "region": "East",
      "plan_k": 757.1,
      "actual_k": 792.5,
      "var_k": 35.4,
      "var_pct": 4.7,
      "disc_pct": 8.1,
      "gm_pct": 34.4
    },
    {
      "month": "2024-12",
      "rep_name": "Mei-Lin Park",
      "region": "East",
      "plan_k": 1100.2,
      "actual_k": 1229.2,
      "var_k": 129.0,
      "var_pct": 11.7,
      "disc_pct": 23.3,
      "gm_pct": 33.0
    },
    {
      "month": "2024-12",
      "rep_name": "Natalie Frost",
      "region": "South",
      "plan_k": 659.9,
      "actual_k": 602.2,
      "var_k": -57.8,
      "var_pct": -8.8,
      "disc_pct": 13.7,
      "gm_pct": 29.3
    },
    {
      "month": "2024-12",
      "rep_name": "Priya Nair",
      "region": "West",
      "plan_k": 583.7,
      "actual_k": 665.2,
      "var_k": 81.4,
      "var_pct": 14.0,
      "disc_pct": 14.6,
      "gm_pct": 42.8
    },
    {
      "month": "2024-12",
      "rep_name": "Rachel Okafor",
      "region": "South",
      "plan_k": 500.4,
      "actual_k": 433.6,
      "var_k": -66.8,
      "var_pct": -13.4,
      "disc_pct": 11.6,
      "gm_pct": 31.8
    },
    {
      "month": "2024-12",
      "rep_name": "Sofia Delgado",
      "region": "East",
      "plan_k": 903.2,
      "actual_k": 698.3,
      "var_k": -204.9,
      "var_pct": -22.7,
      "disc_pct": 16.8,
      "gm_pct": 28.3
    },
    {
      "month": "2024-12",
      "rep_name": "Tyler Brooks",
      "region": "Central",
      "plan_k": 1373.8,
      "actual_k": 1048.7,
      "var_k": -325.1,
      "var_pct": -23.7,
      "disc_pct": 18.6,
      "gm_pct": 28.2
    }
  ],
  "by_region": [
    {
      "region": "Central",
      "reps": 3,
      "avg_attainment": 111.2,
      "total_rev_mm": 20.81,
      "avg_gm": 40.1
    },
    {
      "region": "East",
      "reps": 3,
      "avg_attainment": 103.1,
      "total_rev_mm": 24.84,
      "avg_gm": 35.0
    },
    {
      "region": "South",
      "reps": 3,
      "avg_attainment": 101.8,
      "total_rev_mm": 24.27,
      "avg_gm": 31.0
    },
    {
      "region": "West",
      "reps": 3,
      "avg_attainment": 68.5,
      "total_rev_mm": 13.57,
      "avg_gm": 36.1
    }
  ]
};
